# Generated by Django 4.2.3 on 2023-08-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("productName", models.CharField(max_length=200)),
                ("productReview", models.TextField()),
                ("mallProductUrl", models.TextField()),
            ],
        ),
    ]
