# Generated by Django 4.2.3 on 2023-08-14 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("aspectapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComparisonResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aspect", models.CharField(max_length=20)),
                ("recommendation", models.TextField()),
                (
                    "product1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparisons_as_product1",
                        to="aspectapp.product",
                    ),
                ),
                (
                    "product2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparisons_as_product2",
                        to="aspectapp.product",
                    ),
                ),
            ],
        ),
    ]
