# Generated by Django 4.2.3 on 2023-08-15 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompareList",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selected_object_name",
                    models.CharField(default="not_defined", max_length=100),
                ),
                (
                    "selected_object_url",
                    models.URLField(default="not_defined", max_length=500),
                ),
                (
                    "comparelist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ImageConverters.comparelist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Obj",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_name", models.CharField(max_length=100)),
                ("images", models.JSONField(default="{}")),
                ("comments", models.JSONField(default="{}")),
                ("thumbnail", models.URLField(max_length=500)),
                ("object_url", models.URLField(max_length=500)),
                (
                    "comparelist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ImageConverters.comparelist",
                    ),
                ),
            ],
        ),
    ]
