# Generated by Django 4.2.3 on 2023-08-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ImageConverters", "0002_comparelist_aspects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comparelist",
            name="aspects",
            field=models.CharField(default=[1, 4], max_length=200),
        ),
    ]
