# Generated by Django 4.2.3 on 2023-08-16 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ImageConverters", "0003_alter_comparelist_aspects"),
    ]

    operations = [
        migrations.RenameField(
            model_name="obj",
            old_name="comments",
            new_name="obj_info",
        ),
    ]
