# Generated by Django 4.2.3 on 2023-08-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ImageConverters", "0006_remove_result_selected_object_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comparelist",
            name="aspects",
            field=models.CharField(default=[1, 4], max_length=200),
        ),
    ]
