# Generated by Django 4.2.3 on 2023-08-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ImageConverters", "0007_comparelist_aspects"),
    ]

    operations = [
        migrations.AddField(
            model_name="obj",
            name="comments",
            field=models.JSONField(default="{}"),
        ),
    ]
